language: node_js
node_js:
  - "12"
  - "10"
script: 
  - npm run test
after_success:
  - 'npm run jest --coverage' && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
branches:
  only:
    - master